spring:
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: id
            client-secret: secret
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            scope:
              - identify
            redirectUriTemplate: "{baseUrl}/login/oauth2/code/discord"
            clientName: FourScouts client
        provider:
          discord:
            authorizationUri: https://discordapp.com/api/oauth2/authorize
            tokenUri: https://discordapp.com/api/oauth2/token
            userInfoUri: https://discordapp.com/api/users/@me
            usernameAttribute: username